Adding solutions for two hackerrank questions
swapnanildutta/Hackerrank-Codes pull request #56
Opened 2020-10-04 13:43 UTC by pnjha

2020-10-05 05:42 UTC, swapnanildutta requested changes
Please add the HackerRank Question on top as a comment. Thank you.

2020-10-05 05:43 UTC, swapnanildutta requested changes
Please add the HackerRank Question on top as a comment. Thank you.

2020-10-05 05:56 UTC, pnjha commented
> Please add the HackerRank Question on top as a comment. Thank you.

I have added hackerrank question link as the top comment in the file. Will that be enough for reference?

2020-10-11 16:16 UTC, swapnanildutta approved these changes

2020-10-11 16:16 UTC, merged